### ISSUE TITLE
Allow baker balances to be specified in values.yaml files

### ISSUE THREAD

**Issue by elric1** [tqtezos/tezos-k8s#123]
In the accounts section, we have:
```
accounts:
  - name: foo
  - type: secret
  - key: edskAJKNXCjnscasjncak
 ```
Maybe we should add a starting balance to that section.
