### ISSUE TITLE
In values.yaml, change accounts and nodes from a list to a dictionary

### ISSUE THREAD

**Issue by elric1** [tqtezos/tezos-k8s#124]
Currently, we have:
```
accounts:
  - name: baker0
    type: secret
    key: edskKJNjnsdc786254fadc...
  - name: baker1
    type: secret
    key: edskGtcajkndsc432123cda...
```
Let's consider changing this to:
```
accounts:
  baker0:
    type: secret
    key: edskKJNjnsdc786254fadc...
  baker1:
    type: secret
    key: edskGtcajkndsc432123cda...
```
If we make this change, let's also consider eliminating the type. We can easily inference this from the key itself as the type is encoded into the first few chars of the key. So, we'd end up with:
```
accounts:
  baker0:
     key: edskKJNjnsdc786254fadc...
  baker1:
    key: edskGtcajkndsc432123cda...
```
We should leave the account as a dictionary, because we may want to add additional properties such as the balance as specified in #123.
