### ISSUE TITLE
support for arbitrary structured data to add to parameters.json

### ISSUE THREAD

**Issue by nicolasochem** [tqtezos/tezos-k8s#126]
Our codebase is designed to spawn self-sufficient testnets. In order to spawn actual Tezos testnets, we need a mechanism to add additional data to parameters.json such as:

* commitments, for example:

```
commitments:
  - - btzxxxxx
    - 420657830193
  - - btzyyyyy
    - 420657830193
```

This lets you create a faucet which gives you one of these each time you call it.

`btz` are activation accounts. These can in turn be made into real accounts by using the activate command:

```
activate account new with activation_key [-f --force] [--encrypted]
```

From :
https://tezos.gitlab.io/alpha/cli-commands.html?highlight=faucet

* various parameters such as:

```
 "preserved_cycles": 3,
 "blocks_per_cycle": 512,
 "blocks_per_commitment": 16,
 "blocks_per_roll_snapshot": 32,
 "blocks_per_voting_period": 1024,
 "time_between_blocks": [ "30", "20" ],
 "endorsers_per_block": 32,
 "hard_gas_limit_per_operation": "1040000",
 "hard_gas_limit_per_block": "10400000",
 "proof_of_work_threshold": "70368744177663",
 "tokens_per_roll": "8000000000",
 "michelson_maximum_type_size": 1000,
 "seed_nonce_revelation_tip": "125000",
 "origination_size": 257,
 "block_security_deposit": "512000000",
 "endorsement_security_deposit": "64000000",
 "baking_reward_per_endorsement": [ "1250000", "187500" ],
 "endorsement_reward": [ "1250000", "833333" ],
 "cost_per_byte": "250",
 "hard_storage_limit_per_operation": "60000",
 "test_chain_duration": "61440",
 "quorum_min": 2000,
 "quorum_max": 7000,
 "min_proposal_quorum": 500,
 "initial_endorsers": 24,
 "delay_per_missing_endorsement": "4"
```

* external bakers: bakers not part of the topology that are expected to join the network later, but are allocated rights at genesis
* accounts that just have money but do not bake, these are specified by the public key hash in the bootstrap_accounts

`values.yaml` should support specification of arbitrary parameter data in the genesis key, for example:

```
genesis:
  block: BLGLGMXXGyKKhrwfvBQiEcUWV2mRMocu5Vr2YPwv8zUM78BfJi5
  timestamp: '2021-02-22T18:48:30.138488+00:00'
  parameters:
    commitments:
      - - btzxxxxx
        - 420657830193
      - - btzyyyyy
        - 420657830193
    preserved_cycles: 3
    blocks_per_cycle: 512
    blocks_per_commitment: 16
    blocks_per_roll_snapshot: 32
    blocks_per_voting_period: 1024
    bootstrap_accounts:
    - - edpk... #genesis baker
      - 50000000000000
    - - tz1free.... #account with money in it
      - 10000000000000
```

This parameters object should be merged with the one we generate internally (including the baking accounts internal to the chain) and turned into a parameter.json passed to the activate job. This should be done by `config_generator/entrypoint.py`

The advantage of doing it this way is that there is no extra work needed shall the parameters.json file evolve in future versions of tezos.

The work should be done on top of this PR https://github.com/tqtezos/tezos-k8s/pull/117/files

We should merge PR117 since it simplifies the generation of config.json by removing the complicated argparse logic. We should also remove argparse for generation of parameters json and build it as a native python object instead.

Nice to have: move parameter.json generation into its own init container. The reason it's in the config generator is that I though some pods need both, but it's not true at the end.
