### ISSUE TITLE
Infer a key's type from the key itself

### ISSUE THREAD

**Issue by harryttd** [tqtezos/tezos-k8s#143]
It is redundant to have a `type` field in an account. We can easily infer the type as it's encoded into the first few chars of the key. So, we'd end up with:

```yaml
accounts:
  baker0:
     key: edskKJNjnsdc786254fadc...
  node1:
    key: epkkGtcajkndsc432123cda...
```
`edsk` being a secret key.
`edpk` being a public key.

(Split from issue #124)
