### ISSUE TITLE
The names of the baker/node statefulsets should be templatized in Helm

### ISSUE THREAD

**Issue by harryttd** [tqtezos/tezos-k8s#153]
(Related to the comment https://github.com/tqtezos/tezos-k8s/issues/124#issuecomment-800769187 regarding the dynamic lookup of nodes instead of hardcoding.)

This change is necessary due to the fact that statefulset nodes are named by the following convention:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tezos-baking-node
```
k8s will name the the pods of this statefulset by the name defined in `metadata.name` and append a suffix int. So the first pod will be named ` tezos-baking-node-0`, etc.

We don't want the name hardcoded, because in general it is a bad practice to do this in Helm because names/values can easily be changed. With templates, modifications to values will automatically change the value everywhere the template is used.

In the case of this ticket, every pod  in code will be looking itself up for its own specific values specified in values.yaml. Because the pod names are predictable (statefulset name  + int), the pod is able to know its name (provide by a k8s "downstream api" environment variable). And using its name, look itself up.

So it will look similar to this:

values.yaml:
```yaml
baker_statefulset: # charts/tezos/templates/baker.yaml
  name: tezos-baking-node
  node_type: baking
regular_node_statefulset: # charts/tezos/templates/node.yaml
  name: tezos-node
  node_type: regular
```

statefulset definition:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.baker_statefulset.name }}
spec:
  serviceName: {{ .Values.baker_statefulset.name }}
  selector:
    matchLabels:
      app: {{ .Values.baker_statefulset.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.baker_statefulset.name }}
        appType: tezos
```

And any container needing its pod name will pass `{{ .Values.baker_statefulset.name }}` as an env var. It will also pass a `node_type` because it needs to know what type of node it is i.e. `baker`, `regular`, etc. to find itself in the nodes map.

The headless service names for the statefulsets should also be templatized like the above:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.regular_node_statefulset.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.regular_node_statefulset.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.baker_statefulset.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.baker_statefulset.name }}
```

This allows pod's FQDNs to be consistent with their names, thereby allowing dynamic setting of bootstrap peers instead of hardcoding the peer's FQDNs.
