### ISSUE TITLE
it shouldn't be necessary to explicitly set snapshots to null

### ISSUE THREAD

**Issue by nicolasochem** [tqtezos/tezos-k8s#193]
it shouldn't be necessary to explicitly set snapshots to null when activating a new chain or starting a node in archive mode.

For example:

```
nodes:
  regular:
    tezos-node-0:
      config:
        shell:
          history_mode: archive
  baking: {}
regular_node_statefulset: # charts/tezos/templates/node.yaml
  name: tezos-node
  node_type: regular
  storage_size: 50Gi
node_config_network:
  chain_name: florencenet
images:
    tezos: tezos/tezos:v9.1
full_snapshot_url: null
rolling_snapshot_url: null
```

works, but

```
nodes:
  regular:
    tezos-node-0:
      config:
        shell:
          history_mode: archive
  baking: {}
regular_node_statefulset: # charts/tezos/templates/node.yaml
  name: tezos-node
  node_type: regular
  storage_size: 50Gi
node_config_network:
  chain_name: florencenet
images:
    tezos: tezos/tezos:v9.1
```

gives the following errror in `snapshot-downloader` init container:

```
+ CMD=snapshot-downloader                                                                                                                                                                                                                                  │
│ + shift                                                                                                                                                                                                                                                    │
│ + exec /snapshot-downloader.sh                                                                                                                                                                                                                             │
│ No snapshot URL provide for node, exiting                                                                                                                                                                                                                  │
│ stream closed                                                                                                                                                                                                                                              │
```
