### ISSUE TITLE
Support for multiple keys for each baker in a YAML file

### ISSUE THREAD

**Issue by hai-nguyen-van** [tqtezos/tezos-k8s#214]
As discussed with @elric1, it is not currently supported to give several baker keys to a baker in a `.yaml` file. For instance, the following snippet with trigger an expected behavior (without warnings) and will not be able to use `bootstrap1` and `bootstrap2` keys for the baker process `tezos-baking-node-0`.
```
nodes:
  baking:
    tezos-baking-node-0:
      bake_using_account: bootstrap1 bootstrap2
```
Testing that a baker is able to handle several baker keys is part of our testing targets. I believe this feature request is a matter of high interest.
