### ISSUE TITLE
--number-of-bakers

### ISSUE THREAD

**Issue by nicolasochem** [tqtezos/tezos-k8s#35]
This is an incremental feature on top of what we already have and is worth doing now.

Currently bootstrap-nodes is a k8s deployment while nodes are a k8s statefulset.

* turn bootstrap-nodes into a statefulset
* make the number of bakers configurable on mkchain i.e. `--number-of-bakers` just like `--number-of-nodes`
* --generate-constants should generate the appropriate number of baking accounts
* ensure every baking process in the pods are configured to bake for the account according to the statefulset pod number
* every block should be baked at priority 0. scale down is supported, in which case some blocks will be baked at priority 1 or more.
* scale up is not supported - you must decide at chain creation how many baking accounts you want, after that, changing the baker cycles require on-chain operations and waiting several cycles

**Comment by harryttd** [comment]
Related to #17

**Comment by nicolasochem** [comment]
running `mkchain --number-of-nodes 3 --number-of-bakers 2` should generate the following accounts and nodes in the values yaml file:

```
accounts:
- baker: true
  bootstrap: true
  key: !!binary |
    snip
  name: baker_2
  private: true
- baker: true
  bootstrap: true
  key: !!binary |
    snip
  name: baker_2
  private: true
nodes:
- bake_for: baker_1
- bake_for: baker_2
- {}
```

And passing the yaml above to helm should spin up 2 bakers and one regular node.
